# Generated by Django 5.2.3 on 2026-07-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_checkout_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('simulated', 'Simulated'), ('mpesa', 'M-Pesa'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='mpesa', max_length=20),
        ),
    ]
