# Generated by Django 4.2.19 on 2026-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Direct MP4 URL for the hero background video. Leave blank for default safari video.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Vacay Adventure', max_length=200),
        ),
    ]
