# Generated by Django 4.2.19 on 2026-07-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, help_text='Main tour image (shown in listings). Individual gallery images below.', null=True, upload_to='tours/'),
        ),
    ]
