# Generated by Django 4.2.19 on 2026-07-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourpackage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Available departure date')),
                ('available_seats', models.IntegerField(help_text='Seats available for this date')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Optional price +/- for this date', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_dates', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('tour', 'date')},
            },
        ),
    ]
