# Generated by Django 4.2.19 on 2026-07-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourdate'),
        ('bookings', '0002_alter_booking_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tour_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.tourdate'),
        ),
    ]
